version: 0.0
os: linux

files:
  - source: /BE
    destination: /BE/opt/action-practice
permissions:
  - object: /BE/opt/action-practice/
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: root